### ISSUE TITLE
程序无响应

### ISSUE THREAD

**Issue by Gl4c13r** [LangziFun/LangNetworkTopology3#1]
1-65535全端口扫描貌似会无响应？

**Comment by LangziFun** [comment]
全端口开一个进程足以~

**Comment by Gl4c13r** [comment]
确实是一个进程，等了二十分钟了。。。没有数据出来，默认端口已经扫过一遍，效果很好，赞一个
![image](https://user-images.githubusercontent.com/31760645/70962106-e4a33e00-20be-11ea-9a8a-8a7a86a11725.png)

**Comment by Gl4c13r** [comment]
已解决，我把整个B段分成255个C段了，程序反应快些了，感谢

**Comment by LangziFun** [comment]
好的呢~

**Comment by Gl4c13r** [comment]
生成的报告建议可以再弄个excel或者pdf格式，我这边扫描结束报告的html文件占了32526kb，浏览器打开都直接卡死，尴尬

**Comment by LangziFun** [comment]
收到~
